import type { Entity, Era, HistoricalEvent, TimelineYear } from './types'
import { extraEntities } from './extraEntities'

export const eras: Era[] = [
  { id: 'early-web', label: 'The Early Web', range: '1990–1994', start: 1990, end: 1994, description: 'Protocols, portals, and the first pages.', accent: '#65c7bd', majorEntities: ['mosaic', 'linux', 'irc', 'personal-web'] },
  { id: 'browser-wars', label: 'The Browser Wars', range: '1995–1999', start: 1995, end: 1999, description: 'A million homepages bloom.', accent: '#e5a34e', majorEntities: ['netscape', 'ie', 'yahoo', 'geocities'] },
  { id: 'dot-com', label: 'The Dot-Com Aftermath', range: '2000–2004', start: 2000, end: 2004, description: 'The web learns to survive the crash.', accent: '#9d78df', majorEntities: ['google', 'winxp', 'macos', 'blogs'] },
  { id: 'web-two', label: 'Web 2.0', range: '2005–2009', start: 2005, end: 2009, description: 'The web becomes social and participatory.', accent: '#6bb7a6', majorEntities: ['youtube', 'facebook', 'firefox', 'myspace'] },
  { id: 'mobile', label: 'The Mobile Internet', range: '2010–2014', start: 2010, end: 2014, description: 'A touchscreen in every pocket.', accent: '#6b9fd0', majorEntities: ['iphone', 'android', 'instagram', 'whatsapp'] },
  { id: 'platform', label: 'The Platform Era', range: '2015–2019', start: 2015, end: 2019, description: 'Feeds, creators, and algorithmic life.', accent: '#d96b92', majorEntities: ['facebook', 'twitter', 'reddit', 'twitch'] },
  { id: 'pandemic', label: 'The Pandemic Internet', range: '2020–2022', start: 2020, end: 2022, description: 'Work, school, and culture move online.', accent: '#747de0', majorEntities: ['zoom', 'discord', 'tiktok', 'whatsapp'] },
  { id: 'ai', label: 'The AI Internet', range: '2023–2026', start: 2023, end: 2026, description: 'Interfaces start to speak back.', accent: '#76b79f', majorEntities: ['chatgpt', 'ai-agents', 'github', 'tiktok'] },
]

const e = (entity: Omit<Entity, 'color'> & { color?: string }): Entity => ({ color: '#e2b95f', ...entity })

const baseEntities: Entity[] = [
  e({ id: 'mosaic', name: 'Mosaic', category: 'Browser', shortLabel: 'NCSA Mosaic', symbol: '▦', founded: '1993', ended: '1997', status: 'discontinued', activeYears: { start: 1993, end: 1997 }, tags: ['browser', 'web'], color: '#65c7bd', description: 'The browser that made the web feel visual by putting images beside text.', whyItMattered: 'Mosaic translated the web from a text protocol into a place to look at. Its inline images and approachable interface helped move the internet out of labs and into homes.', links: { wikipedia: 'https://en.wikipedia.org/wiki/Mosaic_(web_browser)' } }),
  e({ id: 'netscape', name: 'Netscape Navigator', category: 'Browser', shortLabel: 'Netscape', symbol: '◒', founded: '1994', ended: '2008', status: 'discontinued', activeYears: { start: 1994, end: 2001 }, tags: ['browser', 'browser wars'], color: '#e5a34e', description: 'The rocket-branded browser that introduced millions to the graphical web.', whyItMattered: 'Netscape made browsing a mainstream activity and turned the browser into a strategic battleground. Its rapid rise set the rhythm for the first browser war.', links: { wikipedia: 'https://en.wikipedia.org/wiki/Netscape_Navigator' } }),
  e({ id: 'ie', name: 'Internet Explorer', category: 'Browser', shortLabel: 'IE', symbol: 'e', founded: '1995', ended: '2022', status: 'discontinued', activeYears: { start: 1995, end: 2015 }, tags: ['browser', 'microsoft'], color: '#58a7d9', description: 'Microsoft’s browser, bundled into Windows and dominant through the early 2000s.', whyItMattered: 'Internet Explorer made the browser an invisible part of the operating system. Its dominance shaped web standards, web development, and the online habits of a generation.', links: { wikipedia: 'https://en.wikipedia.org/wiki/Internet_Explorer' } }),
  e({ id: 'firefox', name: 'Firefox', category: 'Browser', shortLabel: 'Firefox', symbol: '◉', founded: '2004', status: 'active', activeYears: { start: 2004 }, tags: ['browser', 'open source'], color: '#e47742', description: 'The open-source browser that gave users a credible alternative to Internet Explorer.', whyItMattered: 'Firefox proved that an independent, community-built browser could reset expectations around tabs, extensions, privacy, and web standards.', links: { website: 'https://www.mozilla.org/firefox/' } }),
  e({ id: 'chrome', name: 'Chrome', category: 'Browser', shortLabel: 'Chrome', symbol: '◌', founded: '2008', status: 'active', activeYears: { start: 2008 }, tags: ['browser', 'google'], color: '#d8b64f', description: 'Google’s fast, sandboxed browser built for a web of applications.', whyItMattered: 'Chrome pushed the browser toward being an operating system for web apps. Its speed, auto-updates, and engine quickly became the new baseline for the web.', links: { website: 'https://www.google.com/chrome/' } }),
  e({ id: 'yahoo', name: 'Yahoo!', category: 'Search Engine', shortLabel: 'Yahoo!', symbol: 'Y!', founded: '1994', status: 'active', activeYears: { start: 1994 }, tags: ['portal', 'search'], color: '#9d78df', description: 'A human-curated directory that became an early gateway to the web.', whyItMattered: 'Yahoo! helped people navigate an internet that was still small enough to catalog by hand, then evolved into a portal for search, mail, news, and identity.', links: { website: 'https://www.yahoo.com/' } }),
  e({ id: 'altavista', name: 'AltaVista', category: 'Search Engine', shortLabel: 'AltaVista', symbol: 'A', founded: '1995', ended: '2013', status: 'discontinued', activeYears: { start: 1995, end: 2004 }, tags: ['search'], color: '#4eb2a5', description: 'An early full-text search engine known for indexing more of the web.', whyItMattered: 'AltaVista made the growing web searchable at machine scale. It previewed the importance of speed, relevance, and index size before Google refined the formula.', links: { wikipedia: 'https://en.wikipedia.org/wiki/AltaVista' } }),
  e({ id: 'google', name: 'Google', category: 'Search Engine', shortLabel: 'Google', symbol: 'G', founded: '1998', status: 'active', activeYears: { start: 1998 }, tags: ['search', 'company'], color: '#e2b95f', description: 'A search engine that became the dominant gateway to the web.', whyItMattered: 'Google turned the messy web into a daily utility. Its ranking system made finding information feel almost instantaneous and built a new kind of internet infrastructure.', links: { website: 'https://www.google.com/' } }),
  e({ id: 'bing', name: 'Bing', category: 'Search Engine', shortLabel: 'Bing', symbol: 'b', founded: '2009', status: 'active', activeYears: { start: 2009 }, tags: ['search', 'microsoft'], color: '#71b9d4', description: 'Microsoft’s search engine and a long-running Google alternative.', whyItMattered: 'Bing kept search competitive and later became a visible bridge between traditional search and AI-assisted answers.', links: { website: 'https://www.bing.com/' } }),
  e({ id: 'geocities', name: 'GeoCities', category: 'Culture', shortLabel: 'GeoCities', symbol: '⌂', founded: '1994', ended: '2009', status: 'discontinued', activeYears: { start: 1994, end: 2009 }, tags: ['personal web', 'culture'], color: '#db7d55', description: 'A neighborhood-themed host for millions of personal homepages.', whyItMattered: 'GeoCities showed the web as a place people inhabited, decorated, and made strange together. Its pages captured the exuberant, handmade voice of the early internet.', links: { wikipedia: 'https://en.wikipedia.org/wiki/GeoCities' } }),
  e({ id: 'irc', name: 'IRC', category: 'Messaging', shortLabel: 'IRC', symbol: '#', founded: '1988', status: 'active', activeYears: { start: 1990 }, tags: ['chat', 'protocol'], color: '#bf8dd7', description: 'Real-time text channels where communities gathered before social feeds.', whyItMattered: 'IRC introduced the idea that the internet could be a live social space. Its channels, operators, bots, and handles echo through modern chat platforms.', links: { wikipedia: 'https://en.wikipedia.org/wiki/Internet_Relay_Chat' } }),
  e({ id: 'icq', name: 'ICQ', category: 'Messaging', shortLabel: 'ICQ', symbol: '✳', founded: '1996', ended: '2024', status: 'discontinued', activeYears: { start: 1996, end: 2010 }, tags: ['chat', 'instant messaging'], color: '#88c46b', description: 'An early instant messenger recognizable by its “Uh-oh!” alert.', whyItMattered: 'ICQ made online presence personal and persistent. A number, a contact list, and a blinking status quietly changed how people kept in touch.', links: { wikipedia: 'https://en.wikipedia.org/wiki/ICQ' } }),
  e({ id: 'aim', name: 'AIM', category: 'Messaging', shortLabel: 'AIM', symbol: '▰', founded: '1997', ended: '2017', status: 'discontinued', activeYears: { start: 1997, end: 2017 }, tags: ['chat', 'instant messaging'], color: '#e8c95c', description: 'AOL Instant Messenger, the buddy list that defined online adolescence.', whyItMattered: 'AIM made screen names, away messages, and chat windows part of everyday identity. It turned being online into a visible social status.', links: { wikipedia: 'https://en.wikipedia.org/wiki/AIM_(software)' } }),
  e({ id: 'msn', name: 'MSN Messenger', category: 'Messaging', shortLabel: 'MSN Messenger', symbol: '☺', founded: '1999', ended: '2014', status: 'discontinued', activeYears: { start: 1999, end: 2014 }, tags: ['chat', 'microsoft'], color: '#65b77b', description: 'Microsoft’s expressive messenger, full of nudges, winks, and display names.', whyItMattered: 'MSN Messenger gave mass-market chat a playful grammar of presence and emotion. Its contact list was a daily map of who was around.', links: { wikipedia: 'https://en.wikipedia.org/wiki/Windows_Live_Messenger' } }),
  e({ id: 'skype', name: 'Skype', category: 'Messaging', shortLabel: 'Skype', symbol: 'S', founded: '2003', status: 'active', activeYears: { start: 2003 }, tags: ['calling', 'video'], color: '#5da9d5', description: 'Internet calling that made a long-distance voice and video call feel ordinary.', whyItMattered: 'Skype moved reliable voice and video out of the phone network and onto the internet, preparing the cultural ground for remote work and always-on video.', links: { website: 'https://www.skype.com/' } }),
  e({ id: 'whatsapp', name: 'WhatsApp', category: 'Messaging', shortLabel: 'WhatsApp', symbol: '◔', founded: '2009', status: 'active', activeYears: { start: 2009 }, tags: ['mobile', 'chat'], color: '#65be84', description: 'A mobile-first messenger that became a default layer of global communication.', whyItMattered: 'WhatsApp made messaging cheap, mobile, and cross-border. It replaced carrier texting for billions and blurred the line between phone book and social network.', links: { website: 'https://www.whatsapp.com/' } }),
  e({ id: 'discord', name: 'Discord', category: 'Messaging', shortLabel: 'Discord', symbol: '◡', founded: '2015', status: 'active', activeYears: { start: 2015 }, tags: ['chat', 'community'], color: '#747de0', description: 'Voice, video, and text communities built around servers rather than a public feed.', whyItMattered: 'Discord revived the feeling of rooms and persistent communities for a platform era. It became infrastructure for games, fandoms, study groups, and open-source projects.', links: { website: 'https://discord.com/' } }),
  e({ id: 'myspace', name: 'MySpace', category: 'Social Network', shortLabel: 'MySpace', symbol: '★', founded: '2003', status: 'active', activeYears: { start: 2003, end: 2010 }, tags: ['social', 'music'], color: '#d96b92', description: 'A customizable social profile where music, friends, and HTML collided.', whyItMattered: 'MySpace made the profile a public stage. Its messy custom layouts and music-first culture showed that social networks could be expressive personal media.', links: { wikipedia: 'https://en.wikipedia.org/wiki/Myspace' } }),
  e({ id: 'facebook', name: 'Facebook', category: 'Social Network', shortLabel: 'Facebook', symbol: 'f', founded: '2004', status: 'active', activeYears: { start: 2004 }, tags: ['social', 'platform'], color: '#6b91d2', description: 'A real-identity network that scaled from campus directory to global platform.', whyItMattered: 'Facebook moved online social interaction from anonymous forums toward persistent real-identity networks. The feed became a new front door to news, friends, and advertising.', links: { website: 'https://www.facebook.com/' } }),
  e({ id: 'twitter', name: 'Twitter', category: 'Social Network', shortLabel: 'Twitter', symbol: '✦', founded: '2006', status: 'active', activeYears: { start: 2006 }, tags: ['social', 'microblog'], color: '#62b6d5', description: 'Short public posts that turned live events and commentary into a constant stream.', whyItMattered: 'Twitter made the internet feel synchronous. Hashtags, retweets, and a 140-character limit created a new language for breaking news and collective attention.', links: { website: 'https://x.com/' } }),
  e({ id: 'instagram', name: 'Instagram', category: 'Social Network', shortLabel: 'Instagram', symbol: '▣', founded: '2010', status: 'active', activeYears: { start: 2010 }, tags: ['social', 'mobile', 'image'], color: '#e88772', description: 'A camera-first network that made the filtered square a social unit.', whyItMattered: 'Instagram centered the phone camera in social life. It accelerated visual culture, creator economies, and the expectation that every moment could be published.', links: { website: 'https://www.instagram.com/' } }),
  e({ id: 'reddit', name: 'Reddit', category: 'Social Network', shortLabel: 'Reddit', symbol: '▲', founded: '2005', status: 'active', activeYears: { start: 2005 }, tags: ['forum', 'community'], color: '#df7d50', description: 'A network of topic communities organized around links and votes.', whyItMattered: 'Reddit kept the forum alive inside the platform era. Its subreddits made niche knowledge, inside jokes, and collective moderation visible at scale.', links: { website: 'https://www.reddit.com/' } }),
  e({ id: 'tiktok', name: 'TikTok', category: 'Social Network', shortLabel: 'TikTok', symbol: '♪', founded: '2016', status: 'active', activeYears: { start: 2016 }, tags: ['social', 'short video'], color: '#df6d85', description: 'An algorithmic short-video feed that turned the swipe into a global stage.', whyItMattered: 'TikTok made recommendation, remix, and short video the default grammar of discovery. It shifted influence away from follower graphs toward algorithmic taste.', links: { website: 'https://www.tiktok.com/' } }),
  e({ id: 'realplayer', name: 'RealPlayer', category: 'Video', shortLabel: 'RealPlayer', symbol: '▶', founded: '1995', status: 'discontinued', activeYears: { start: 1995, end: 2013 }, tags: ['video', 'streaming'], color: '#84be66', description: 'One of the first popular players for audio and video over the internet.', whyItMattered: 'RealPlayer made “streaming” tangible, even when buffering was part of the experience. It proved media could be delivered as a live network service.', links: { wikipedia: 'https://en.wikipedia.org/wiki/RealPlayer' } }),
  e({ id: 'youtube', name: 'YouTube', category: 'Video', shortLabel: 'YouTube', symbol: '▶', founded: '2005', status: 'active', activeYears: { start: 2005 }, tags: ['video', 'creator'], color: '#e36a5a', description: 'A video platform that made publishing and watching globally searchable.', whyItMattered: 'YouTube made the internet a broadcast medium for everyone. It collapsed the distance between bedroom creator, global audience, archive, and algorithm.', links: { website: 'https://www.youtube.com/' } }),
  e({ id: 'netflix', name: 'Netflix', category: 'Video', shortLabel: 'Netflix', symbol: 'N', founded: '1997', status: 'active', activeYears: { start: 2007 }, tags: ['video', 'streaming'], color: '#d64551', description: 'A DVD-by-mail company that became the emblem of streaming television.', whyItMattered: 'Netflix helped normalize on-demand video libraries and binge watching. It moved entertainment from schedules and shelves into the cloud.', links: { website: 'https://www.netflix.com/' } }),
  e({ id: 'twitch', name: 'Twitch', category: 'Video', shortLabel: 'Twitch', symbol: '▰', founded: '2011', status: 'active', activeYears: { start: 2011 }, tags: ['video', 'live'], color: '#8f73d2', description: 'Live streaming with a chat window that made audiences feel present.', whyItMattered: 'Twitch turned watching someone else play, make, or talk into a participatory live format. Chat became part of the show.', links: { website: 'https://www.twitch.tv/' } }),
  e({ id: 'win95', name: 'Windows 95', category: 'Operating System', shortLabel: 'Windows 95', symbol: '⊞', founded: '1995', ended: '2001', status: 'discontinued', activeYears: { start: 1995, end: 2001 }, tags: ['os', 'microsoft'], color: '#62a9cf', description: 'The Start menu, taskbar, and dial-up era desktop that defined a generation.', whyItMattered: 'Windows 95 made connecting to the internet a household ritual. Its desktop metaphors shaped how millions understood files, programs, and being online.', links: { wikipedia: 'https://en.wikipedia.org/wiki/Windows_95' } }),
  e({ id: 'winxp', name: 'Windows XP', category: 'Operating System', shortLabel: 'Windows XP', symbol: '⊞', founded: '2001', ended: '2014', status: 'discontinued', activeYears: { start: 2001, end: 2014 }, tags: ['os', 'microsoft'], color: '#5d9fce', description: 'A long-lived, colorful operating system that carried the web into the broadband era.', whyItMattered: 'XP was the background to a huge expansion of home internet. It made digital cameras, instant messaging, games, and browsers feel like one connected desktop.', links: { wikipedia: 'https://en.wikipedia.org/wiki/Windows_XP' } }),
  e({ id: 'macos', name: 'Mac OS X', category: 'Operating System', shortLabel: 'Mac OS X', symbol: '⌘', founded: '2001', status: 'active', activeYears: { start: 2001 }, tags: ['os', 'apple'], color: '#9ca8b4', description: 'Apple’s Unix-based desktop system with a polished, media-friendly interface.', whyItMattered: 'Mac OS X made the Unix foundation feel approachable and helped position the personal computer as a creative internet studio.', links: { wikipedia: 'https://en.wikipedia.org/wiki/MacOS' } }),
  e({ id: 'ios', name: 'iOS', category: 'Operating System', shortLabel: 'iOS', symbol: '◉', founded: '2007', status: 'active', activeYears: { start: 2007 }, tags: ['mobile', 'os', 'apple'], color: '#a1b8d2', description: 'The touch-first operating system that made the smartphone a software platform.', whyItMattered: 'iOS turned the web into a pocket-sized app ecosystem. It made location, camera, sensors, and notifications part of everyday computing.', links: { website: 'https://www.apple.com/ios/' } }),
  e({ id: 'android', name: 'Android', category: 'Operating System', shortLabel: 'Android', symbol: '♟', founded: '2008', status: 'active', activeYears: { start: 2008 }, tags: ['mobile', 'os', 'google'], color: '#7fc38a', description: 'An open mobile platform that put internet-connected smartphones in many hands.', whyItMattered: 'Android expanded the mobile internet across price points, manufacturers, and countries. It made the smartphone a global computing baseline.', links: { website: 'https://www.android.com/' } }),
  e({ id: 'linux', name: 'Linux', category: 'Operating System', shortLabel: 'Linux', symbol: '◖', founded: '1991', status: 'active', activeYears: { start: 1991 }, tags: ['os', 'open source'], color: '#d1a554', description: 'An open-source operating system that became quiet infrastructure for the internet.', whyItMattered: 'Linux showed that a global community could build and maintain core computing infrastructure. It powers servers, supercomputers, phones, and developer culture.', links: { website: 'https://www.kernel.org/' } }),
  e({ id: 'dialup', name: 'Dial-up Modem', category: 'Hardware', shortLabel: 'Dial-up', symbol: '⌁', founded: '1980s', ended: '2010s', status: 'discontinued', activeYears: { start: 1990, end: 2005 }, tags: ['hardware', 'access'], color: '#ba9f78', description: 'The noisy handshake that connected a home computer to the wider world.', whyItMattered: 'Dial-up made access feel physical and finite. The busy signal, shared phone line, and patient loading bar taught early users that the network had a texture.', links: { wikipedia: 'https://en.wikipedia.org/wiki/Dial-up_Internet_access' } }),
  e({ id: 'ipod', name: 'iPod', category: 'Hardware', shortLabel: 'iPod', symbol: '◉', founded: '2001', ended: '2022', status: 'discontinued', activeYears: { start: 2001, end: 2015 }, tags: ['hardware', 'music'], color: '#d0d1cc', description: 'A pocket music player that helped make digital media feel personal and portable.', whyItMattered: 'The iPod trained people to carry libraries in their pockets and helped set the stage for the app-shaped smartphone.', links: { wikipedia: 'https://en.wikipedia.org/wiki/IPod' } }),
  e({ id: 'iphone', name: 'iPhone', category: 'Hardware', shortLabel: 'iPhone', symbol: '▯', founded: '2007', status: 'active', activeYears: { start: 2007 }, tags: ['hardware', 'mobile'], color: '#b8c1cb', description: 'A touch-screen computer that collapsed phone, camera, browser, and app store.', whyItMattered: 'The iPhone changed the internet’s center of gravity from desk to pocket. Every service had to become mobile, immediate, and sensor-aware.', links: { website: 'https://www.apple.com/iphone/' } }),
  e({ id: 'raspberry-pi', name: 'Raspberry Pi', category: 'Hardware', shortLabel: 'Raspberry Pi', symbol: '●', founded: '2012', status: 'active', activeYears: { start: 2012 }, tags: ['hardware', 'maker'], color: '#cb6e69', description: 'An affordable tiny computer that put tinkering back within reach.', whyItMattered: 'Raspberry Pi made computing physical, hackable, and educational again. It connected the maker movement to the old promise of a computer for everyone.', links: { website: 'https://www.raspberrypi.com/' } }),
  e({ id: 'personal-web', name: 'Personal Websites', category: 'Culture', shortLabel: 'Homepages', symbol: '✧', founded: '1990s', status: 'active', activeYears: { start: 1990 }, tags: ['culture', 'personal web'], color: '#e3b95a', description: 'Handmade pages, guestbooks, blinking badges, and a URL of one’s own.', whyItMattered: 'Personal websites made publishing feel like a basic right of internet citizenship. They were small, weird, and proudly outside a feed.', links: { wikipedia: 'https://en.wikipedia.org/wiki/Personal_web_page' } }),
  e({ id: 'forums', name: 'Forums', category: 'Culture', shortLabel: 'Forums', symbol: '☷', founded: '1990s', status: 'active', activeYears: { start: 1990 }, tags: ['culture', 'community'], color: '#aa8ccf', description: 'Threaded conversations organized around interests, questions, and regulars.', whyItMattered: 'Forums gave the web memory. A question could be answered, archived, and found years later by someone else who needed it.', links: { wikipedia: 'https://en.wikipedia.org/wiki/Internet_forum' } }),
  e({ id: 'blogs', name: 'Blogs', category: 'Culture', shortLabel: 'Blogs', symbol: '✎', founded: '1999', status: 'active', activeYears: { start: 1999 }, tags: ['culture', 'publishing'], color: '#d58f5f', description: 'Chronological publishing tools that made a personal voice easy to update.', whyItMattered: 'Blogs lowered the cost of publishing and helped create the link economy. They gave the web a daily pulse before social feeds took over.', links: { wikipedia: 'https://en.wikipedia.org/wiki/Blog' } }),
  e({ id: 'web2', name: 'Web 2.0', category: 'Culture', shortLabel: 'Web 2.0', symbol: '✦', founded: '2004', status: 'active', activeYears: { start: 2004 }, tags: ['culture', 'platform'], color: '#6bb7a6', description: 'A shorthand for participatory sites, APIs, tags, and user-generated content.', whyItMattered: 'Web 2.0 described a shift from reading pages to using platforms. The web became interactive, social, and increasingly dependent on its users.', links: { wikipedia: 'https://en.wikipedia.org/wiki/Web_2.0' } }),
  e({ id: 'memes', name: 'Memes', category: 'Culture', shortLabel: 'Memes', symbol: '☻', founded: '1990s', status: 'active', activeYears: { start: 1990 }, tags: ['culture', 'humor'], color: '#d86e7d', description: 'Replicable jokes and images that mutate as they cross communities.', whyItMattered: 'Memes made culture feel programmable. A template, caption, and remix could travel faster than any editorial institution.', links: { wikipedia: 'https://en.wikipedia.org/wiki/Internet_meme' } }),
  e({ id: 'chatgpt', name: 'ChatGPT', category: 'AI', shortLabel: 'ChatGPT', symbol: '✺', founded: '2022', status: 'active', activeYears: { start: 2022 }, tags: ['ai', 'interface'], color: '#76b79f', description: 'A conversational interface that brought generative AI into everyday use.', whyItMattered: 'ChatGPT made talking to a model feel like a general-purpose internet activity. It shifted attention from searching for pages to asking systems to compose answers.', links: { website: 'https://chatgpt.com/' } }),
  e({ id: 'ai-agents', name: 'AI Agents', category: 'AI', shortLabel: 'AI agents', symbol: '◎', founded: '2023', status: 'active', activeYears: { start: 2023 }, tags: ['ai', 'automation'], color: '#83a9db', description: 'Software that can plan, use tools, and act across digital environments.', whyItMattered: 'AI agents suggest a new internet interaction model: people describe outcomes while software navigates the interfaces and services on their behalf.', links: { wikipedia: 'https://en.wikipedia.org/wiki/Intelligent_agent' } }),
  e({ id: 'github', name: 'GitHub', category: 'Platform', shortLabel: 'GitHub', symbol: '◉', founded: '2008', status: 'active', activeYears: { start: 2008 }, tags: ['developer', 'open source', 'platform'], color: '#b7a7d0', description: 'A social home for code, collaboration, and open-source history.', whyItMattered: 'GitHub made software development legible as a social practice. Repositories, pull requests, and profiles turned collaboration into a visible public record.', links: { website: 'https://github.com/' } }),
  e({ id: 'zoom', name: 'Zoom', category: 'Video', shortLabel: 'Zoom', symbol: '▣', founded: '2011', status: 'active', activeYears: { start: 2013 }, tags: ['video', 'remote'], color: '#71a8d4', description: 'A video meeting service that became a verb during the pandemic internet.', whyItMattered: 'Zoom compressed the distance between a classroom, office, family table, and stage. Its grid view became one of the defining images of 2020.', links: { website: 'https://zoom.us/' } }),
]

const relationshipMap: Record<string, Partial<Entity>> = {
  google: { relatedIds: ['chrome', 'youtube', 'android'], competitors: ['yahoo', 'bing'], milestones: [{ year: 1998, title: 'Founded', detail: 'Google is incorporated around a new approach to ranking the web.' }, { year: 2000, title: 'AdWords', detail: 'Search advertising becomes a major part of the web economy.' }, { year: 2004, title: 'IPO', detail: 'Google enters the public markets.' }, { year: 2008, title: 'Chrome', detail: 'A new browser puts Google closer to the web runtime.' }, { year: 2015, title: 'Alphabet', detail: 'The company reorganizes under Alphabet.' }, { year: 2023, title: 'AI transformation', detail: 'Generative AI reshapes the search interface.' }] },
  facebook: { relatedIds: ['instagram', 'whatsapp', 'threads'], competitors: ['myspace', 'twitter'], milestones: [{ year: 2004, title: 'Founded', detail: 'A campus network begins in Cambridge, Massachusetts.' }, { year: 2006, title: 'Open registration', detail: 'The network opens beyond universities.' }, { year: 2012, title: 'Instagram', detail: 'Facebook acquires Instagram.' }, { year: 2021, title: 'Meta', detail: 'The parent company adopts the Meta name.' }] },
  microsoft: { relatedIds: ['ie', 'msn', 'win95', 'winxp', 'win11'], competitors: ['apple', 'google'], milestones: [{ year: 1975, title: 'Founded', detail: 'Microsoft begins by making software for personal computers.' }, { year: 1985, title: 'Windows', detail: 'The graphical operating system starts its long run.' }, { year: 1995, title: 'Windows 95', detail: 'The Start menu brings computing to a mass audience.' }, { year: 1995, title: 'Internet Explorer', detail: 'The browser becomes part of the Windows story.' }, { year: 2023, title: 'AI partnership', detail: 'AI becomes a visible layer across Microsoft products.' }] },
  apple: { relatedIds: ['macos', 'iphone', 'ios', 'ipod', 'safari'], competitors: ['microsoft', 'android'], milestones: [{ year: 1976, title: 'Founded', detail: 'Apple begins with a personal computer built for ordinary users.' }, { year: 2001, title: 'iPod', detail: 'A pocket music library changes personal media.' }, { year: 2007, title: 'iPhone', detail: 'The touch screen changes the center of gravity of the web.' }, { year: 2008, title: 'App Store', detail: 'The phone becomes a platform for downloadable software.' }] },
  youtube: { relatedIds: ['google', 'twitch', 'netflix', 'vimeo'], competitors: ['vimeo', 'dailymotion'], milestones: [{ year: 2005, title: 'Founded', detail: 'A simple upload flow points toward a new broadcast medium.' }, { year: 2006, title: 'Google acquisition', detail: 'YouTube joins Google and scales its infrastructure.' }, { year: 2010, title: 'Creator era', detail: 'Channels, subscriptions, and recommendation become a new career path.' }] },
  chatgpt: { relatedIds: ['ai-agents', 'openai', 'google'], competitors: ['bing', 'google'], milestones: [{ year: 2022, title: 'Public release', detail: 'A conversational interface brings generative AI to a mass audience.' }, { year: 2023, title: 'Multimodal turn', detail: 'Text, image, and tool use begin to converge.' }] },
  netscape: { relatedIds: ['mosaic', 'ie', 'firefox'], competitors: ['ie', 'mosaic'], milestones: [{ year: 1994, title: 'Founded', detail: 'Netscape brings a fast graphical browser to the public web.' }, { year: 1995, title: 'Browser wars', detail: 'The browser becomes the strategic center of the web.' }] },
  iphone: { relatedIds: ['apple', 'ios', 'android', 'instagram'], competitors: ['android-phone', 'blackberry'], milestones: [{ year: 2007, title: 'Launch', detail: 'A touch-first computer makes the internet portable.' }, { year: 2008, title: 'App Store', detail: 'Third-party apps turn the phone into a platform.' }] },
}

export const entities: Entity[] = [...baseEntities, ...extraEntities].map((entity) => ({ ...entity, ...relationshipMap[entity.id] }))

export const timelineYears: TimelineYear[] = [
  { year: 1990, title: 'The web is taking shape', description: 'At CERN, the first web server and browser turn a proposal into a working system.', internetUsers: 'Not yet measured', popularBrowser: 'WorldWideWeb (NeXT)', majorPlatform: 'CERN web project', majorTrend: 'Hypertext', entities: ['irc', 'personal-web'], events: [{ date: 'Dec 1990', title: 'The first web server runs at CERN', detail: 'By Christmas 1990, the first server and browser are running at CERN; the first public website follows in 1991.' }] },
  { year: 1993, title: 'The web gets a window', description: 'Images, browsers, and public access turn a research project into a medium.', internetUsers: '≈ 14M', popularBrowser: 'Mosaic', majorPlatform: 'NCSA Mosaic', majorTrend: 'Graphical web', entities: ['mosaic', 'irc', 'linux', 'personal-web'], events: [{ date: 'Apr 1993', title: 'Mosaic is released', detail: 'The graphical browser makes inline images feel natural.' }] },
  { year: 1995, title: 'The browser wars begin', description: 'Homepages multiply, portals compete, and the sound of a modem becomes a ritual.', internetUsers: '≈ 44M', popularBrowser: 'Netscape Navigator', majorPlatform: 'Yahoo!', majorTrend: 'Dial-up access', entities: ['netscape', 'yahoo', 'geocities', 'irc', 'win95', 'dialup', 'personal-web'], events: [{ date: 'Aug 1995', title: 'Windows 95 launches', detail: 'The Start menu and dial-up networking put a new desktop in millions of homes.' }] },
  { year: 1997, title: 'The homepage is a neighborhood', description: 'The web feels handmade, social, and just a little bit chaotic.', internetUsers: '≈ 117M', popularBrowser: 'Netscape Navigator', majorPlatform: 'GeoCities', majorTrend: 'Personal publishing', entities: ['netscape', 'yahoo', 'geocities', 'aim', 'win95', 'forums', 'memes'], events: [{ date: 'May 1997', title: 'AIM arrives', detail: 'The buddy list turns being online into a visible social status.' }] },
  { year: 1999, title: 'The portal is the front door', description: 'Search, chat, and glossy portals make the internet feel like a destination.', internetUsers: '≈ 280M', popularBrowser: 'Internet Explorer 5', majorPlatform: 'Yahoo!', majorTrend: 'Portal culture', entities: ['ie', 'yahoo', 'altavista', 'msn', 'blogs', 'forums'], events: [{ date: '1999', title: 'Blogger makes publishing easier', detail: 'Blogger launches a hosted publishing tool that lowers the barrier to keeping a personal site.' }] },
  { year: 2001, title: 'The web survives the crash', description: 'The dot-com bubble bursts, but search, broadband, and open source keep moving.', internetUsers: '≈ 500M', popularBrowser: 'Internet Explorer 6', majorPlatform: 'Google', majorTrend: 'Broadband', entities: ['google', 'ie', 'winxp', 'macos', 'linux', 'ipod', 'forums'], events: [{ date: 'Jan 15, 2001', title: 'Wikipedia launches', detail: 'The first Wikipedia edition opens as a collaboratively edited encyclopedia.' }] },
  { year: 2003, title: 'Profiles become places', description: 'Social networks, Skype, and blogs turn identity into something you can update.', internetUsers: '≈ 730M', popularBrowser: 'Internet Explorer 6', majorPlatform: 'MySpace', majorTrend: 'Social profiles', entities: ['google', 'ie', 'myspace', 'skype', 'blogs', 'winxp'], events: [{ date: 'Aug 2003', title: 'MySpace goes live', detail: 'The profile becomes a personal stage for friends, music, and HTML.' }] },
  { year: 2005, title: 'Welcome to Web 2.0', description: 'The web becomes participatory: upload, comment, tag, subscribe, repeat.', internetUsers: '≈ 1.0B', popularBrowser: 'Internet Explorer 6', majorPlatform: 'YouTube', majorTrend: 'User-generated content', entities: ['google', 'ie', 'firefox', 'youtube', 'myspace', 'reddit', 'msn', 'web2', 'blogs', 'winxp', 'ipod'], events: [{ date: 'Feb 2005', title: 'YouTube is founded', detail: 'A simple upload button points toward a new broadcast medium.' }] },
  { year: 2007, title: 'The pocket becomes a platform', description: 'A touch screen changes where the internet lives and what it can notice.', internetUsers: '≈ 1.4B', popularBrowser: 'Safari (iPhone)', majorPlatform: 'YouTube', majorTrend: 'Mobile internet', entities: ['youtube', 'facebook', 'twitter', 'iphone', 'ios', 'netflix', 'web2'], events: [{ date: 'Jun 29, 2007', title: 'The iPhone ships', detail: 'Apple puts the first iPhone on sale in the United States, combining phone, iPod, and internet device.' }] },
  { year: 2010, title: 'Everything is a feed', description: 'The camera, the status update, and the infinite scroll converge.', internetUsers: '≈ 2.0B', popularBrowser: 'Chrome', majorPlatform: 'Facebook', majorTrend: 'Social mobile', entities: ['chrome', 'facebook', 'twitter', 'instagram', 'android', 'ios', 'youtube', 'netflix', 'whatsapp'], events: [{ date: 'Oct 2010', title: 'Instagram launches', detail: 'The filtered square makes the phone camera a social unit.' }] },
  { year: 2012, title: 'The network gets visual', description: 'Phones, apps, and creator platforms make sharing feel like a reflex.', internetUsers: '≈ 2.5B', popularBrowser: 'Chrome', majorPlatform: 'Facebook', majorTrend: 'App ecosystems', entities: ['chrome', 'facebook', 'instagram', 'reddit', 'whatsapp', 'android', 'iphone', 'raspberry-pi', 'twitch'], events: [{ date: 'Apr 2012', title: 'Facebook announces Instagram acquisition', detail: 'Facebook announces an agreement to acquire the photo app, subject to closing conditions.' }] },
  { year: 2015, title: 'The platform era', description: 'Feeds become infrastructure. Creators, communities, and algorithms share one stage.', internetUsers: '≈ 3.2B', popularBrowser: 'Chrome', majorPlatform: 'Facebook', majorTrend: 'Algorithmic feeds', entities: ['chrome', 'facebook', 'twitter', 'instagram', 'reddit', 'twitch', 'whatsapp', 'discord', 'android', 'ios'], events: [{ date: '2015', title: 'Discord launches', detail: 'Community chat finds a home between forum, group text, and voice room.' }] },
  { year: 2018, title: 'The feed learns your taste', description: 'Short video, stories, and recommendations turn attention into the main currency.', internetUsers: '≈ 3.9B', popularBrowser: 'Chrome', majorPlatform: 'YouTube', majorTrend: 'Recommendation', entities: ['chrome', 'instagram', 'reddit', 'youtube', 'twitch', 'discord', 'tiktok', 'android', 'ios'], events: [{ date: '2018', title: 'Short video takes over', detail: 'The swipe becomes a new way to discover culture.' }] },
  { year: 2020, title: 'The pandemic internet', description: 'Work, school, culture, and friendship move through webcams and shared documents.', internetUsers: '≈ 4.6B', popularBrowser: 'Chrome', majorPlatform: 'YouTube', majorTrend: 'Remote everything', entities: ['chrome', 'youtube', 'discord', 'twitch', 'zoom', 'whatsapp', 'tiktok', 'android', 'ios'], events: [{ date: '2020', title: 'The network becomes a lifeline', detail: 'Video calls and chat rooms absorb daily life at global scale.' }] },
  { year: 2023, title: 'The AI internet', description: 'Interfaces begin to write, see, summarize, and act alongside us.', internetUsers: '≈ 5.4B', popularBrowser: 'Chrome', majorPlatform: 'ChatGPT', majorTrend: 'Generative AI', entities: ['chrome', 'chatgpt', 'ai-agents', 'tiktok', 'youtube', 'discord', 'github', 'android', 'ios'], events: [{ date: '2023', title: 'Conversational interfaces go mainstream', detail: 'Generative AI becomes a new way to ask the internet for help.' }] },
  { year: 2026, title: 'A web that talks back', description: 'The browser is becoming a collaborator: part archive, part tool, part agent.', internetUsers: 'Latest known: ≈ 5.5B (2024 estimate)', popularBrowser: 'Chrome / Edge', majorPlatform: 'AI assistants', majorTrend: 'Agentic interfaces', entities: ['chrome', 'google', 'chatgpt', 'ai-agents', 'tiktok', 'youtube', 'discord', 'github', 'android', 'ios', 'iphone', 'android-phone'], events: [{ date: '2026', title: 'A forward-looking snapshot', detail: 'This is a present-day curation point, not a completed historical measurement; user totals use the latest available estimate.' }] },
]

export const getEntity = (id: string) => entities.find((entity) => entity.id === id)
// A selected year must never display a later exhibit. The final node is the latest
// known snapshot, so years between nodes use the most recent prior snapshot.
export const getYear = (year: number) => timelineYears.reduce((previous, item) => item.year <= year && item.year > previous.year ? item : previous, timelineYears[0])
export const getEra = (year: number) => eras.find((era) => year >= era.start && year <= era.end) ?? eras[0]

const eventNotes: Record<string, Pick<HistoricalEvent, 'whyItMattered' | 'importance' | 'sources'>> = {
  'The first web server runs at CERN': { whyItMattered: 'CERN records this as the point when the Web moved from proposal to a working server and browser.', importance: 'high', sources: [{ title: 'CERN: The birth of the Web', url: 'https://home.cern/science/computing/the-birth-of-the-web/' }] },
  'Mosaic is released': { whyItMattered: 'NCSA Mosaic made inline images and point-and-click browsing familiar to a much wider audience.', importance: 'high', sources: [{ title: 'NCSA: Mosaic browser history', url: 'https://www.ncsa.illinois.edu/research/project-highlights/ncsa-mosaic/' }] },
  'Windows 95 launches': { whyItMattered: 'Windows 95 bundled a consumer desktop and network tools that helped make home web access routine.', importance: 'medium', sources: [{ title: 'Microsoft: Windows 95', url: 'https://news.microsoft.com/1995/08/24/windows-95-launches/' }] },
  'Blogger makes publishing easier': { whyItMattered: 'Hosted blogging reduced the technical cost of publishing regular updates on the Web.', importance: 'medium', sources: [{ title: 'Official Blogger Blog: Happy Birthday Blogger!', url: 'https://blogger.googleblog.com/2006/08/happy-birthday-blogger.html' }] },
  'Wikipedia launches': { whyItMattered: 'Wikipedia demonstrated that a public reference work could be built and maintained collaboratively online.', importance: 'high', sources: [{ title: 'Wikipedia: About', url: 'https://en.wikipedia.org/wiki/Wikipedia:About' }] },
  'MySpace goes live': { whyItMattered: 'MySpace made the customizable social profile a mainstream form of online identity.', importance: 'medium', sources: [{ title: 'Myspace: About', url: 'https://myspace.com/pages/about' }] },
  'YouTube is founded': { whyItMattered: 'YouTube lowered the friction of sharing video online and helped make user-uploaded media a default web format.', importance: 'high', sources: [{ title: 'YouTube: About', url: 'https://www.youtube.com/about/' }] },
  'The iPhone ships': { whyItMattered: 'The iPhone combined a phone, iPod, and internet device, helping move everyday web use from desk to pocket.', importance: 'high', sources: [{ title: 'Apple: iPhone premieres', url: 'https://www.apple.com/newsroom/2007/06/28iPhone-Premieres-This-Friday-Night-at-Apple-Retail-Stores/' }] },
  'Instagram launches': { whyItMattered: 'Instagram made the phone camera a social publishing tool built around lightweight visual sharing.', importance: 'medium', sources: [{ title: 'Instagram: About us', url: 'https://about.instagram.com/about-us' }] },
  'Facebook announces Instagram acquisition': { whyItMattered: 'The announcement showed how rapidly a major platform could absorb a mobile-native social format.', importance: 'medium', sources: [{ title: 'Meta: Facebook to acquire Instagram', url: 'https://about.fb.com/news/2012/04/facebook-to-acquire-instagram/' }] },
  'Discord launches': { whyItMattered: 'Discord brought persistent text, voice, and community rooms together for online groups.', importance: 'medium', sources: [{ title: 'Discord: About', url: 'https://discord.com/company' }] },
  'AIM arrives': { whyItMattered: 'AIM made online presence visible through buddy lists, screen names, and away messages.', importance: 'medium', sources: [{ title: 'AOL: AIM announcement archive', url: 'https://help.aol.com/articles/aim-discontinued' }] },
  'Short video takes over': { whyItMattered: 'By the late 2010s, short vertical video and recommendation feeds had become a major way to discover culture.', importance: 'medium', sources: [{ title: 'TikTok Newsroom', url: 'https://newsroom.tiktok.com/en-us/about-tiktok' }] },
  'The network becomes a lifeline': { whyItMattered: 'The COVID-19 pandemic made video meetings, messaging, and shared online workspaces essential to everyday continuity.', importance: 'high', sources: [{ title: 'ITU: Measuring digital development', url: 'https://www.itu.int/itu-d/reports/statistics/facts-figures-2020/' }] },
  'Conversational interfaces go mainstream': { whyItMattered: 'Generative AI services made natural-language interaction a widely visible consumer interface.', importance: 'high', sources: [{ title: 'OpenAI: Introducing ChatGPT', url: 'https://openai.com/index/chatgpt/' }] },
  'A forward-looking snapshot': { whyItMattered: 'This entry records the current curation horizon; future claims are deliberately kept as a snapshot rather than presented as settled history.', importance: 'low', sources: [{ title: 'ITU: Facts and Figures', url: 'https://www.itu.int/itu-d/reports/statistics/facts-figures-2024/' }] },
}

export const historicalEvents: HistoricalEvent[] = timelineYears.flatMap((year) => year.events.map((event, index) => ({
  id: `${year.year}-${index}-${event.title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`,
  year: year.year,
  date: event.date,
  title: event.title,
  description: event.detail,
  whyItMattered: eventNotes[event.title]?.whyItMattered ?? 'This documented moment changed how people encountered the network.',
  entities: year.entities,
  importance: eventNotes[event.title]?.importance ?? 'medium',
  sources: eventNotes[event.title]?.sources ?? [{ title: 'CERN: The birth of the Web', url: 'https://home.cern/science/computing/the-birth-of-the-web/' }],
})))
