import type { Entity } from './types'

export type EntityCopy = Pick<Entity, 'name' | 'description' | 'whyItMattered' | 'category'>

// Explicit Chinese editorial copy for every extended exhibit.
export const extraEntityCopy: Record<string, EntityCopy> = {
  'safari': { name: 'Safari', category: '浏览器', description: '苹果推出的网页浏览器，强调渲染性能与设备整合。', whyItMattered: '它把浏览器体验深度嵌入苹果生态，并推动了移动网页的发展。' },
  'opera': { name: 'Opera', category: '浏览器', description: '以标签页、速度和界面实验著称的独立浏览器。', whyItMattered: '它持续证明网页客户端可以保持多样化。' },
  'edge': { name: 'Microsoft Edge', category: '浏览器', description: '微软面向现代网页推出的浏览器，后来采用 Chromium 基础。', whyItMattered: '它记录了浏览器竞争从专属引擎走向共享引擎的变化。' },
  'konqueror': { name: 'Konqueror', category: '浏览器', description: 'KDE 桌面中的浏览器与文件管理器。', whyItMattered: '它把 Linux 桌面的本地文件和网络访问放进同一套工具。' },
  'brave': { name: 'Brave', category: '浏览器', description: '强调隐私、防追踪和替代广告模式的浏览器。', whyItMattered: '它让隐私成为普通用户可以主动选择的浏览体验。' },
  'vivaldi': { name: 'Vivaldi', category: '浏览器', description: '面向高级用户、强调深度定制的浏览器。', whyItMattered: '它延续了浏览器界面应由用户塑造的传统。' },
  'lynx': { name: 'Lynx', category: '浏览器', description: '以纯文本方式访问网页的浏览器。', whyItMattered: '它保留了低带宽、命令行和辅助访问在网页历史中的位置。' },
  'seamonkey': { name: 'SeaMonkey', category: '浏览器', description: '由社区延续的 Mozilla 经典互联网套件。', whyItMattered: '它保存了早期浏览器、邮件等工具合在一起的工作方式。' },
  'ask-jeeves': { name: 'Ask Jeeves', category: '搜索引擎', description: '以管家形象和自然语言提问为特色的搜索服务。', whyItMattered: '它提前展示了人们希望用完整问题寻找答案的习惯。' },
  'duckduckgo': { name: 'DuckDuckGo', category: '搜索引擎', description: '把减少追踪和隐私保护放在前面的搜索引擎。', whyItMattered: '它让隐私成为搜索产品之间可见的比较维度。' },
  'lycos': { name: 'Lycos', category: '搜索引擎', description: '早期网页繁荣时期的搜索引擎与门户。', whyItMattered: '它保存了搜索、邮件、新闻和娱乐集中在门户首页的形态。' },
  'excite': { name: 'Excite', category: '搜索引擎', description: '受互联网泡沫影响的门户和搜索服务。', whyItMattered: '它体现了早期门户争夺网络入口的竞争。' },
  'dogpile': { name: 'Dogpile', category: '搜索引擎', description: '把多个搜索引擎结果汇集在一起的元搜索服务。', whyItMattered: '它让用户看见搜索结果背后的索引聚合过程。' },
  'baidu': { name: '百度', category: '搜索引擎', description: '面向中文互联网的重要搜索与内容服务。', whyItMattered: '它展现了语言、市场和本地内容对搜索基础设施的塑造。' },
  'yandex': { name: 'Yandex', category: '搜索引擎', description: '服务俄语互联网并扩展到多种数字服务的技术公司。', whyItMattered: '它说明搜索产品会深受语言、地理和本地生态影响。' },
  'naver-search': { name: 'Naver', category: '搜索引擎', description: '韩国的综合门户，结合搜索、内容、购物和社区。', whyItMattered: '它体现了搜索入口与本土内容平台融合的区域路径。' },
  'snapchat': { name: 'Snapchat', category: '社交网络', description: '以限时消息、相机滤镜和故事功能为核心的移动社交应用。', whyItMattered: '它把短暂分享和镜头效果变成社交媒体的日常语言。' },
  'tumblr': { name: 'Tumblr', category: '社交网络', description: '以转发、博客排版和同人社群为特色的社交出版平台。', whyItMattered: '它让混剪、亚文化和个人身份在同一信息流中相遇。' },
  'linkedin': { name: 'LinkedIn', category: '社交网络', description: '围绕职业履历、招聘和工作关系建立的实名网络。', whyItMattered: '它把个人资料变成持续更新的职业名片。' },
  'pinterest': { name: 'Pinterest', category: '社交网络', description: '以图板、收藏和视觉搜索组织内容的网络。', whyItMattered: '它把寻找灵感从浏览行为变成可积累的个人资料库。' },
  'weibo': { name: 'Sina Weibo', category: '社交网络', description: '面向公共讨论、媒体传播和名人文化的中文微博平台。', whyItMattered: '它形成了具有本地特色的公开信息流和网络评论节奏。' },
  'mixi': { name: 'Mixi', category: '社交网络', description: '日本早期以熟人社群和信任关系为特色的社交网络。', whyItMattered: '它说明社交产品可以围绕半私密关系发展，而不只依赖公开信息流。' },
  'hi5': { name: 'Hi5', category: '社交网络', description: '曾在多个地区拥有大量用户的全球社交网络。', whyItMattered: '它保留了早期平台竞争具有地区差异的证据。' },
  'orkut': { name: 'Orkut', category: '社交网络', description: 'Google 运营、在巴西和印度形成重要社区的社交网络。', whyItMattered: '它说明同一全球平台会因本地用户而产生不同文化。' },
  'threads': { name: 'Threads', category: '社交网络', description: '与 Instagram 身份体系相连的文字社交网络。', whyItMattered: '它展示了成熟平台借助既有身份网络建立新社交空间的方式。' },
  'bluesky': { name: 'Bluesky', category: '社交网络', description: '探索可迁移身份和去中心化协议的社交网络。', whyItMattered: '它让开放社交协议重新进入平台设计讨论。' },
  'telegram': { name: 'Telegram', category: '即时通讯', description: '支持大群组、频道和机器人的云端通讯工具。', whyItMattered: '它把私人消息延伸为广播、社区和可编程空间。' },
  'wechat': { name: '微信', category: '即时通讯', description: '结合聊天、支付、媒体和生活服务的中国超级应用。', whyItMattered: '它把日常生活的多个数字入口收进一个移动工具。' },
  'qq': { name: 'QQ', category: '即时通讯', description: '以头像、游戏和社交功能影响一代中国网民的即时通讯工具。', whyItMattered: '它把网名、好友关系和青年文化连接成长期数字身份。' },
  'line': { name: 'LINE', category: '即时通讯', description: '以贴纸和移动聊天为特色、在日本及周边地区广泛使用的通讯工具。', whyItMattered: '它证明本地设计语言可以成为区域平台的核心竞争力。' },
  'kakao-talk': { name: 'KakaoTalk', category: '即时通讯', description: '韩国常用的移动通讯工具，并延伸到支付、媒体和生活服务。', whyItMattered: '它把消息入口发展成韩国数字生活的重要平台。' },
  'google-talk': { name: 'Google Talk', category: '即时通讯', description: 'Google 早期提供的轻量文字聊天与语音服务。', whyItMattered: '它把电子邮件身份与实时沟通联系起来。' },
  'hangouts': { name: 'Google Hangouts', category: '即时通讯', description: '整合聊天、语音和视频会话的 Google 通讯服务。', whyItMattered: '它体现了互联网长期把消息、电话和会议合并的尝试。' },
  'signal': { name: 'Signal', category: '即时通讯', description: '以端到端加密和隐私保护为核心的通讯工具。', whyItMattered: '它让强加密成为普通用户可以使用的通信期待。' },
  'kik': { name: 'Kik', category: '即时通讯', description: '以用户名而非电话号码建立联系的移动通讯工具。', whyItMattered: '它把网名和匿名社交传统带进智能手机消息时代。' },
  'viber': { name: 'Viber', category: '即时通讯', description: '提供消息和网络通话、拥有国际用户群的移动应用。', whyItMattered: '它体现了移动通信竞争长期具有地区性和多语言特征。' },
  'vimeo': { name: 'Vimeo', category: '视频', description: '面向创作者和电影社群的视频平台。', whyItMattered: '它证明网络视频可以服务于作品展示，而不只是大众流量。' },
  'dailymotion': { name: 'Dailymotion', category: '视频', description: '起源于欧洲、面向全球发展的在线视频平台。', whyItMattered: '它保存了早期视频网络更加多元的竞争格局。' },
  'bilibili': { name: 'Bilibili', category: '视频', description: '由动画、游戏和滚动评论文化塑造的中文视频社区。', whyItMattered: '它把同好文化和同步评论变成视频平台的核心体验。' },
  'douyin': { name: 'Douyin', category: '视频', description: '以推荐、竖屏短视频和混剪为核心的中国平台。', whyItMattered: '它推动了短视频推荐机制和创作语法的发展。' },
  'periscope': { name: 'Periscope', category: '视频', description: '后来并入 Twitter 的移动直播应用。', whyItMattered: '它帮助直播从电视式节目变成手机原生的社交格式。' },
  'crunchyroll': { name: 'Crunchyroll', category: '视频', description: '围绕动画内容和全球粉丝社群建立的流媒体服务。', whyItMattered: '它让小众文化成为具有国际规模的合法流媒体市场。' },
  'hulu': { name: 'Hulu', category: '视频', description: '由电视公司推动、面向网络发行的流媒体服务。', whyItMattered: '它记录了电视节目从固定播出转向合法按需观看的过渡。' },
  'blogger': { name: 'Blogger', category: '平台', description: '让个人网站能够持续更新的托管式博客工具。', whyItMattered: '它降低了发布门槛，推动网络从手写页面走向持续出版。' },
  'wordpress': { name: 'WordPress', category: '平台', description: '从博客发展为开放、可扩展的网站发布系统。', whyItMattered: '它让公开出版保持开放，并成为大量网站的基础。' },
  'wikipedia': { name: 'Wikipedia', category: '平台', description: '由志愿者共同编辑、向所有人开放的在线百科全书。', whyItMattered: '它让集体知识生产成为网络持久的公共制度。' },
  'stack-overflow': { name: 'Stack Overflow', category: '平台', description: '面向程序员的问答网站和技术社区。', whyItMattered: '它把可搜索的同行经验变成软件工作的日常基础设施。' },
  'craigslist': { name: 'Craigslist', category: '平台', description: '坚持简洁设计、服务本地分类信息的网络平台。', whyItMattered: '它说明实用性和地方性可以长期胜过视觉潮流。' },
  'ebay': { name: 'eBay', category: '平台', description: '以刊登、竞价和陌生人信任为基础的在线市场。', whyItMattered: '它让个人之间进行跨地域交易变得日常。' },
  'amazon': { name: 'Amazon', category: '平台', description: '从图书销售扩展到零售、云计算和物流基础设施的网络公司。', whyItMattered: '它把搜索、购物、仓储、云服务和日常生活连接起来。' },
  'etsy': { name: 'Etsy', category: '平台', description: '面向手工艺品和独立卖家的在线市场。', whyItMattered: '它为小型创作者提供了面向全球买家的数字店面。' },
  'yahoo-japan': { name: 'Yahoo! Japan', category: '平台', description: '在日本发展成重要本地网络入口的门户。', whyItMattered: '它展示了全球品牌如何在本地成长为独立区域生态。' },
  'taobao': { name: '淘宝', category: '平台', description: '以小商家、互动购物和直播销售为特色的中国电商平台。', whyItMattered: '它参与塑造了中国高度互动的电商文化。' },
  'aliexpress': { name: 'AliExpress', category: '平台', description: '连接中国卖家与全球消费者的跨境电商平台。', whyItMattered: '它让日常商品交易的跨境平台化变得可见。' },
  'steam': { name: 'Steam', category: '平台', description: '提供 PC 游戏数字发行、自动更新和社区功能的平台。', whyItMattered: '它让可下载游戏库和数字化游戏所有权成为常态。' },
  'win98': { name: 'Windows 98', category: '操作系统', description: '在网页进入更多家庭时推出的 Windows 桌面系统。', whyItMattered: '它把熟悉的个人电脑桌面与扩张中的消费互联网连接起来。' },
  'vista': { name: 'Windows Vista', category: '操作系统', description: '采用玻璃质感视觉设计、强调安全和硬件加速的 Windows 版本。', whyItMattered: '它记录了桌面系统在视觉、性能和安全之间的重新取舍。' },
  'win7': { name: 'Windows 7', category: '操作系统', description: '稳定、简洁、面向宽带时代的 Windows 桌面系统。', whyItMattered: '它在 Vista 之后稳定了许多人的日常上网桌面。' },
  'win8': { name: 'Windows 8', category: '操作系统', description: '试图把触控界面带入传统桌面的 Windows 版本。', whyItMattered: '它把桌面软件与移动界面之间的张力带到所有用户面前。' },
  'win10': { name: 'Windows 10', category: '操作系统', description: '面向持续更新和服务化交付的 Windows 系统。', whyItMattered: '它让操作系统从一次购买的产品转向持续演进的服务。' },
  'win11': { name: 'Windows 11', category: '操作系统', description: '采用居中界面、云协作和 AI 功能的现代 Windows 系统。', whyItMattered: '它展示了桌面、云服务、协作和智能功能的进一步融合。' },
  'chromeos': { name: 'ChromeOS', category: '操作系统', description: '围绕浏览器和云服务组织起来的轻量操作系统。', whyItMattered: '它让浏览器从应用之一变成大众电脑的主要工作环境。' },
  'ubuntu': { name: 'Ubuntu', category: '操作系统', description: '把 Linux 开源系统带给更多普通桌面用户的发行版。', whyItMattered: '它让 Linux 从服务器故事扩展为可识别的桌面选择。' },
  'palm-os': { name: 'Palm OS', category: '操作系统', description: '为早期掌上电脑和电子记事本设计的移动操作系统。', whyItMattered: '它提前建立了后来移动平台不断改进的交互习惯。' },
  'symbian': { name: 'Symbian', category: '操作系统', description: '曾经广泛用于早期智能手机的移动操作系统。', whyItMattered: '它说明智能手机平台竞争早在现代应用商店出现之前就已开始。' },
  'ibm-pc': { name: 'IBM PC', category: '硬件', description: '推动兼容机生态形成的个人电脑硬件标准。', whyItMattered: '它让计算机变得模块化、可竞争，并能由许多厂商生产。' },
  'macintosh': { name: 'Macintosh', category: '硬件', description: '苹果推出的图形化个人电脑系列。', whyItMattered: '它让图形桌面和直接操作成为面向人的计算体验。' },
  'android-phone': { name: 'Android phone', category: '硬件', description: '围绕 Android 平台形成的多厂商触控手机家族。', whyItMattered: '它把联网能力从单一高端设备扩展到更多价格和市场。' },
  'google-glass': { name: 'Google Glass', category: '硬件', description: '把摄像头和显示屏戴在眼前的可穿戴设备。', whyItMattered: '它迫使公众讨论摄像头、隐私和手机之后的界面。' },
  'vr-headsets': { name: 'VR headsets', category: '硬件', description: '把用户置于计算机生成环境中的消费级头戴设备。', whyItMattered: '它延续了下一代互联网可能走向空间化的想象。' },
  'blackberry': { name: 'BlackBerry', category: '硬件', description: '以安全邮件和实体键盘著称的手机产品线。', whyItMattered: '它在触控手机重置期待之前，先让工作邮件进入口袋。' },
  'nokia-communicator': { name: 'Nokia Communicator', category: '硬件', description: '较早把电话、消息和办公工具结合起来的手机电脑。', whyItMattered: '它说明移动计算在 iPhone 之前已经有过多种形态。' },
  'kindle': { name: 'Kindle', category: '硬件', description: '把个人电子书库放进联网专用设备的电子阅读器。', whyItMattered: '它让数字阅读拥有了比浏览器标签更像实体物品的形态。' },
  'chromebook': { name: 'Chromebook', category: '硬件', description: '围绕 ChromeOS 和云服务设计的低价笔记本电脑。', whyItMattered: '它让以浏览器为中心的计算在学校和轻办公场景普及。' },
  'game-boy': { name: 'Game Boy', category: '硬件', description: '让便携式游戏和掌上计算成为大众文化的任天堂设备。', whyItMattered: '它预示了数字生活最终会随人移动的文化期待。' },
  'microsoft': { name: 'Microsoft', category: '公司', description: '通过操作系统和软件工具影响个人计算与网络生活的公司。', whyItMattered: '它把共同的桌面环境带进数百万家庭。' },
  'apple': { name: 'Apple', category: '公司', description: '覆盖个人电脑、音乐播放器、手机和数字服务的科技公司。', whyItMattered: '它多次改变个人计算的外形、操作方式和情感体验。' },
  'meta': { name: 'Meta', category: '公司', description: '运营多个社交、消息和虚拟世界产品的科技公司。', whyItMattered: '它代表社交身份、广告、通讯和虚拟世界愿景的集中化。' },
  'bytedance': { name: 'ByteDance', category: '公司', description: '以推荐系统驱动 TikTok 和 Douyin 的科技公司。', whyItMattered: '它把算法发现而非关注关系推到短视频文化中心。' },
  'tencent': { name: 'Tencent', category: '公司', description: '拥有 QQ、WeChat、游戏和多种数字服务的中国科技公司。', whyItMattered: '它展示了消息工具如何成为完整数字经济的底层入口。' },
  'alibaba-company': { name: 'Alibaba', category: '公司', description: '以电商、支付、物流和云服务为核心的中国科技集团。', whyItMattered: '它参与构建了彼此强化的市场、支付、物流与云服务生态。' },
  'baidu-company': { name: '百度', category: '公司', description: '以搜索、人工智能和在线服务为核心的中国科技公司。', whyItMattered: '它连接了中国搜索基础设施与后来发展的人工智能方向。' },
  'samsung': { name: 'Samsung', category: '公司', description: '覆盖电子设备、手机、显示屏和芯片的韩国科技集团。', whyItMattered: '它让先进联网硬件成为全球多市场的日常体验。' },
  'sony': { name: 'Sony', category: '公司', description: '长期连接电子设备、音乐、游戏和娱乐内容的日本公司。', whyItMattered: '它以硬件、内容和游戏的结合预示了平台化思维。' },
  'nintendo': { name: 'Nintendo', category: '公司', description: '把游戏、角色和封闭数字世界发展成持久文化的日本公司。', whyItMattered: '它提醒我们互联网文化也由独立、欢乐且有边界的世界塑造。' },
  'spotify': { name: 'Spotify', category: '公司', description: '以海量点播目录和算法歌单为特色的音乐流媒体公司。', whyItMattered: '它让按访问而非购买拥有音乐，以及算法推荐，成为日常文化。' },
  'openai': { name: 'OpenAI', category: '公司', description: '参与推动近期生成式人工智能浪潮的研究与产品公司。', whyItMattered: '它帮助语言模型界面成为大众可直接体验的产品。' },
  'sap': { name: 'SAP', category: '公司', description: '为企业组织和供应链提供软件基础设施的欧洲公司。', whyItMattered: '它说明互联网也深刻改变了看不见的组织系统与商业流程。' },
  'adobe': { name: 'Adobe', category: '公司', description: '以创意工具影响数字出版、设计和媒体制作的软件公司。', whyItMattered: '它帮助网页从文档媒介发展为视觉与多媒体画布。' },
  'intel': { name: 'Intel', category: '公司', description: '长期支撑兼容机和服务器时代的半导体公司。', whyItMattered: '它的处理器为不断扩大的软件和网络技术栈提供物理基础。' },
  'ibm-company': { name: 'IBM', category: '公司', description: '连接大型机、个人电脑、企业系统和计算研究的公司。', whyItMattered: '它把前网络计算时代与后来联网生活的基础设施连接起来。' },
  'huawei': { name: 'Huawei', category: '公司', description: '参与电信网络设备和联网终端建设的中国科技公司。', whyItMattered: '它提醒我们互联网历史同样是网络基础设施的历史。' },
  'rakuten': { name: 'Rakuten', category: '公司', description: '覆盖电商、金融科技和数字服务的日本互联网公司。', whyItMattered: '它参与发展了不同于全球门户的日本平台经济。' },
  'web-rings': { name: 'Web rings', category: '网络文化', description: '把一组个人网站连成共同兴趣圈的链接机制。', whyItMattered: '它在没有中心信息流的时代提供了发现路径和邻里感。' },
  'flash': { name: 'Flash', category: '网络文化', description: '曾为网页带来动画、小游戏和多媒体实验的插件。', whyItMattered: '它让浏览器在现代网页标准成熟前就像一个创意运行环境。' },
  'fan-sites': { name: 'Fan sites', category: '网络文化', description: '由爱好者制作、分享特定兴趣的非官方网页。', whyItMattered: '它展示了网络如何在机构之外成为热爱的劳动成果。' },
  'p2p': { name: 'Peer-to-peer', category: '网络文化', description: '让用户之间直接共享文件或服务的分布式方式。', whyItMattered: '它挑战了互联网必须围绕中心服务器组织的想法。' },
  'torrents': { name: 'Torrents', category: '网络文化', description: '让多个用户共同分发大文件的分布式传输方式。', whyItMattered: '它展示了分布式分发的韧性，也暴露了技术与版权的张力。' },
  'influencers': { name: 'Influencers', category: '网络文化', description: '围绕个人品牌、受众和赞助形成的创作者文化。', whyItMattered: '它把可见度、信任和受众转化为新的媒体商业模式。' },
  'streaming': { name: 'Streaming culture', category: '网络文化', description: '围绕按需观看和收听形成的媒体消费文化。', whyItMattered: '它把媒体从可拥有的物件变成持续提供的服务关系。' },
  'online-communities': { name: 'Online communities', category: '网络文化', description: '跨越论坛、聊天、游戏和平台形成的兴趣共同体。', whyItMattered: '它是每个互联网时代底层的社会基础设施。' },
  'social-media': { name: '社交媒体', category: '网络文化', description: '围绕发布、关注、回应和分享形成的广义网络文化。', whyItMattered: '它把受众、身份和注意力变成网络公共生活的主要语法。' },
  'short-video': { name: '短视频', category: '网络文化', description: '为竖屏、推荐和混剪优化的快速视频形式。', whyItMattered: '它让算法发现与参与式表演变得难以分开。' },
  'ai-generated-content': { name: 'AI-generated content', category: '人工智能', description: '使用生成式模型制作的文字、图像、音频和视频。', whyItMattered: '它改变了媒体制作的成本和速度，也带来作者身份与信任问题。' },
  'ascii-art': { name: 'ASCII 字符画', category: '网络文化', description: '在纯文本环境中用字符排列组成的图像。', whyItMattered: 'ASCII 字符画证明创造力早于图形界面，并能适应每一代媒介。' },
  'guestbooks': { name: '留言簿', category: '网络文化', description: '附在个人网站上的小型留言表单。', whyItMattered: '留言簿让早期网站在评论区和社交信息流出现前就具有往返关系。' },
  'open-source': { name: '开源文化', category: '网络文化', description: '公开分享、修改和维护软件的协作文化。', whyItMattered: '开源把软件变成协作公地，并支撑了大量现代互联网基础设施。' },
  'net-art': { name: '网络艺术', category: '网络文化', description: '直接以网络协议、用户和故障为材料创作的艺术。', whyItMattered: '网络艺术把互联网当成作品的材料和场所，而不只是传播渠道。' },
  'cybercafes': { name: '网吧', category: '网络文化', description: '在个人宽带普及前提供公共电脑和上网服务的空间。', whyItMattered: '网吧让互联网访问成为社会化、公共化且可负担的体验。' },
}


